name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        shell: pwsh
        run: dotnet restore .\CashTracker.sln

      - name: Build
        shell: pwsh
        run: dotnet build .\CashTracker.sln --no-restore --configuration Release

      - name: Test
        shell: pwsh
        run: dotnet test .\CashTracker.sln --no-build --configuration Release --logger "console;verbosity=minimal"
